[development]
HIGHLIGHT = ["some", "streamers"]
KODI_JSONRPC = 'http://radxa.labs:8080/jsonrpc'
CLIENT_ID = 'fill this in'
CLIENT_SECRET = 'fill this in'
VOD_USERS = ["vixella"]
CEC_TOPIC = 'KODI_ON'
MQTT_HOST = 'iot.labs'
